function(my_get_llvm_version)
    cmake_parse_arguments(PARSE_ARGV 0 arg "" "MAJOR;MINOR;PATCH" "")

    # Check if we're using Clang.
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        message(WARNING "my_get_llvm_version: Current compiler is not Clang (it's ${CMAKE_CXX_COMPILER_ID})")
        if(arg_MAJOR)
            set(${arg_MAJOR} "" PARENT_SCOPE)
        endif()
        if(arg_MINOR)
            set(${arg_MINOR} "" PARENT_SCOPE)
        endif()
        if(arg_PATCH)
            set(${arg_PATCH} "" PARENT_SCOPE)
        endif()
        return()
    endif()

    string(REPLACE "." ";" LLVM_VERSION ${CMAKE_CXX_COMPILER_VERSION})
    list(GET LLVM_VERSION 0 MAJOR)
    list(GET LLVM_VERSION 1 MINOR)
    list(GET LLVM_VERSION 2 PATCH)

    if(arg_MAJOR)
        set(${arg_MAJOR} ${MAJOR} PARENT_SCOPE)
    endif()
    if(arg_MINOR)
        set(${arg_MINOR} ${MINOR} PARENT_SCOPE)
    endif()
    if(arg_PATCH)
        set(${arg_PATCH} ${PATCH} PARENT_SCOPE)
    endif()
endfunction()
