name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        target:
          - x64-linux-gcc
          - x64-linux-clang
        include:
          - target: x64-linux-gcc
            os: ubuntu-latest
            preset: gcc
            build_type: Release
          - target: x64-linux-clang
            os: ubuntu-latest
            preset: clang
            build_type: Release

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        cat << EOF >> "$GITHUB_OUTPUT"
        build-output-dir=${{ github.workspace }}/build
        EOF

    - name: Configure CMake
      run: >
        cmake
        -S ${{ github.workspace }}
        -B ${{ steps.strings.outputs.build-output-dir }}
        --preset=${{ matrix.preset }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
