name: Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        preset:
          - gcc
          - clang
        sanitizer:
          - asan
          - tsan
        os: [ubuntu-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        cat << EOF >> "$GITHUB_ENV"
        SANITIZER=${{ matrix.sanitizer }}
        EOF

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        cat << EOF >> "$GITHUB_OUTPUT"
        build-output-dir=${{ github.workspace }}/build
        EOF

    - name: Configure CMake
      run: >
        cmake
        -L
        -S ${{ github.workspace }}
        -B ${{ steps.strings.outputs.build-output-dir }}
        --preset=${{ matrix.preset }}
        -DCOROFX_ENABLE_${SANITIZER^^}=ON

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
